name: aws-ssm
description: Inject SSM Parameters as environment variables into your build step.
author: https://github.com/blstrco
public: false
requirements:
  - aws
  - bash
configuration:
  properties:
    parameters:
      type: object
    region:
      type: string
  required:
    - parameters
  additionalProperties: false
